### ISSUE TITLE
waiting for the network should be optional

### ISSUE THREAD

**Issue by rmanly** [chilcote/outset#18]
I was banging against what I thought was yoyo being yoyo when I was trying to do some network profiles and time settings via outset at first boot.

Turns out that outset was just waiting for the network to come up and no network was setup at the time of firstboot.

[This][] is a possible implementation…provided outset is moved from sys.argv to argparse.

[This]: https://github.com/rmanly/outset/commit/8bdb62e7bf0c48ebdc004d574fb68ef9b61b30a6#diff-7e9a8014e9a9073a06e9602c54bb2173

**Comment by erikng** [comment]
Shouldn't there be a time to give up?

**Comment by rmanly** [comment]
That would be good too.

But in the ideal implementation the sysadmin could pick the timeout and then there are even more arguments to parse. ;)

**Comment by rmanly** [comment]
;)

https://github.com/rmanly/outset/commit/bbcd1c14d0b7e004f68120f2e6f94c368174c6be

**Comment by chilcote** [comment]
To me, firstboot means "immediately after provisioning" (imaging or whatnot), and any scripts I put in there will want to have network active before execution.  Otherwise scripts may or may not work (i.e. munki kickstart or jamf policy).

What I would do with scripts that I want to run when the mac turns on, and I don't care about an active network connection, is I'd put them in every-boot and add a self destruct line at the end.

I'd rather not add a whole other launchd plist just to allow for the option to not wait for network.  

I think maybe what I'll do is add your if statement and then put in the docs that you can edit the plist with the extra arg if you don't want to require networking for firstboot scripts. 

As for a timeout,  If you have a timeout and let the scripts run without network, then you may as well just run the scripts without a network.  I can add a timeout and which continues the regular boot process and  logs something like "ensure network and reboot again, or yadda yadda."

**Comment by chilcote** [comment]
Ryan can you try the ondemand branch and see if it will bypass the network wait? Add the `--do-not-wait` flag to `com.github.outset.boot.plist`

**Comment by chilcote** [comment]
Ryan, actually I think I have a better method.  Can you try this (https://dl.dropboxusercontent.com/u/610494/outset_script-1.0.1.pkg)? There's now a plist at /usr/local/outset/com.chilcote.outset.plist. Change the wait_for_network bit from true to false, and outset should bypass all the loginwindow and network waiting stuff. This way there's no funny bizness with the launchdaemons.

**Comment by rmanly** [comment]
I'll check out your new pkg in a bit.

I just included the "new" launchd plist as an example. My intention was to just have the option commented out but I ran into the xml comment problem with it ending on the "--" in --boot-no-wait.

Now that you explain your thinking between firstboot and everyboot that makes sense and would be a way for me to get around the "issues" I was having. Should've thought of that. Instance of missing the forest for the trees.

**Comment by chilcote** [comment]
You had the right idea. This default setting has always bothered me (and I've heard from others that it's a nuisance), and I had toyed with the idea of taking out the network wait altogether. But it's still useful for the scenarios mentioned. Your prompt made me actually think through it. Hopefully adding this option will be enough. And having a pref file should be useful down the line too, e.g I'll add in a user customizable timeout so it won't run ad infinitum to this patch.

**Comment by chilcote** [comment]
Try this updated pkg: https://dl.dropboxusercontent.com/u/610494/outset_script-1.0.1.pkg

Should now bail after 3 minutes of no network.

**Comment by rmanly** [comment]
Did you see my link up top?

I wrote a way to specify a timeout defaulting to 1 hour.

It does add another option to the plist though.

Wasn't sure if you missed it was it was just a link above and not a pull request or anything.

https://github.com/rmanly/outset/commit/bbcd1c14d0b7e004f68120f2e6f94c368174c6be

**Comment by chilcote** [comment]
Yeah I missed that. One hour seems long... wouldn't you give up before then if it was sitting at the startup progress bar?  Do you think defaulting to three minutes is too short?  Are there environments where it takes longer than three minutes for an active network connection to come online?  I'm sure this will become more of a problem as Apple moves more to only using wi-fi, but that's a bridge that can be crossed later.

I'd also like to avoid advising people to edit the launchd plist.   The current method of waiting 10 seconds between checks I think is better than checking-checking-checking like that.  I'm OCD that way. Anyway, let me know if it works.

**Comment by erikng** [comment]
With a large network over here (200,000+ devices) it can take up to 30 seconds and sometimes just a tad more to get a network connection. 3 minutes seems like enough unless perhaps someone forgets to plug in a network cable?

**Comment by chilcote** [comment]
OK thanks.

I have a new update (https://github.com/chilcote/outset/commit/3a11445b5e7fbc7d4115140a3aac339e183da19e). Would you mind testing this pkg: https://dl.dropboxusercontent.com/u/610494/outset_script-1.0.1_timeout.pkg

It will default to 180 seconds (three minutes) but you can change that value in the com.chilcote.outset.plist.

It should now continue to run everyboot-scripts and firstboot-packages even if the network is unplugged. Only firstboot-scripts will be bypassed, and an error is written to /var/log/outset.log.

**Comment by chilcote** [comment]
included in latest push to master

**Comment by aysiu** [comment]
I've had a couple of people with login screen hangs, which I believe are related to this, because changing the timeout to 1 instead of 180 in the preferences file fixes the hang (they're on Yosemite—oddly, there's no need to change the preference in El Capitan).

Is that the preferred method to fixing the issue (changing the number to a lower number)?

**Comment by chilcote** [comment]
What do you mean by "login screen hangs?"  The network time out will suppress the login screen until there is a network connection, so you'll see the apple logo indefinitely. 

Info on configuring the network timeout is here: https://github.com/chilcote/outset/wiki/NetworkTimeout.  If that's wrong or not clear let me know.

**Comment by aysiu** [comment]
Oh, totally makes sense, then. So turning it to false or a smaller number would be the sanctioned way to avoid that. Thanks for the link.

**Comment by erikng** [comment]
I forgot about this feature. Could there possibly be a preference for wait for network when only first boot packages are present and then one for all other boots? This might explain some weirdness I had at my old job.

**Comment by aysiu** [comment]
> Could there possibly be a preference for wait for network when only first boot packages are present and then one for all other boots?

Perhaps you could have one of your first-boot package deliver a payload of a new preferences file that turns off wait-for-network?

**Comment by chilcote** [comment]
@erikng It will only wait for network for `boot-once`, not `boot-every`, items if `network_wait` is set to True. https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L347-L350

**Comment by aysiu** [comment]
Would you consider a pull request that would allow first-boot scripts to run without a network connection if the .plist wait_for_network is set to false?

**Comment by chilcote** [comment]
That's how it currently works.

**Comment by aysiu** [comment]
That's what I thought when I glanced at the code. For some reason, it doesn't seem to be working for me. Should the .plist be formatted as
```<key>wait_for_network</key>
<false/>```

I've tried that, but it still seems to be deciding that it will wait for the network and skip running the boot-once scripts. Perhaps I'm formatting it incorrectly?

**Comment by chilcote** [comment]
Oh... heh... ahem.  That's a bug.  Can you try changing this value to False and see if it behaves the way you expect?

https://github.com/chilcote/outset/blob/master/pkgroot/usr/local/outset/outset#L319

**Comment by chilcote** [comment]
Just pushed a fix.  See if that works for values of True and False in the plist now.

**Comment by erikng** [comment]
@chilcote okay got it. Cool.

**Comment by aysiu** [comment]
Thanks, chilcote. I'll try it out tomorrow and report back!

**Comment by aysiu** [comment]
Just tested it. Totally works. Tried it with the flag set to true—didn't run. Tried it with the flag set to false—ran.

**Comment by chilcote** [comment]
Glad to hear it, thanks for finding that one.

**Comment by aysiu** [comment]
Thanks for fixing it so quickly! Amazing!

**Comment by chilcote** [comment]
@aysiu @erikng Bringing this back up.  Since we changed the default wait_for_network to False, I've had a chance to update my process for creating a new VM with outset (See! I do use outset, despite the rumors!).  Turns out, I don't like defaulting to False.  Too many of my setup scripts failed (setting the hostname, downloading vagrant ssh key, etc.) because there was no network stack.

I think we fixed the reported problem, which was that manually setting wait_for_network to False in the plist was failing, but we introduced a new one, which is that it now defaults to False instead of True.  This might be a breaking change for admins used to the current behavior.  

What do you think if I revert it wait_for_network to True, which would again mean that one would have to deploy a custom plist to change that to False?

**Comment by erikng** [comment]
I have no skin in the game. It sounds like a breaking change, so do it.

**Comment by rmanly** [comment]
With the bug fixed it's no biggie for me to set to false where/when needed.

**Comment by aysiu** [comment]
I like the idea, as long as it works to change the .plist to false, which I wasn't finding. I'd be happy to test the change, though.

**Comment by chilcote** [comment]
Please do.  It worked, changing that key to False, but I'll take any validation I can.  (Seriously, if you can give me validation in any other areas of my life, I'll take that too!)

**Comment by aysiu** [comment]
Yup. Working now. Just tested it with 2.0.3, and it's all good. Also added it to AutoPkgr, so I won't be behind again.
