### ISSUE TITLE
timestamp OR sha1?

### ISSUE THREAD

**Issue by arubdesu** [chilcote/outset#20]
Current behavior is that it won't re-run a script if it has the same name. Which is a feature, no doubt, but I'm wondering if other behavior can be added for `login-once`'s, maybe via an `optparse`-included option like '--trigger', to match a sha1? Therefore updating the login-once script would cause a fresh run. Normal warnings about trying to make sure checks are in place so this doesn't cause undesirable behavior is warranted, but seems advantageous to at least support as an arg: temporarily override the launchA for that flag, change it back after compliance is met.
Scope creep?

**Comment by erikng** [comment]
This is actually a good idea. I get around this by inserting my own time stamp into my scripts and placing them in login-every. When I push a change to my script I update the time stamp (scripts also contain logic to differentiate between first run and subsequent).

**Comment by chilcote** [comment]
Yeah I have something similar in the works.  I think a sha1 check in general is a better way than just the name.  Stay tuned.

**Comment by erikng** [comment]
One thing I thought of is there may be times where I want to update a login-once script, but actually choose to still only run it for new users.

If something like this is implemented, we need to make sure the admin has some way to identify between the two.

**Comment by chilcote** [comment]
Erik, that sounds like a different request.  Can you open that in a new issue?  Something like: "need the ability to add login-once scripts but only for new user logins, not existing ones."

I'm not saying this will be implemented, but it's just a different request than what Allister is asking for.

**Comment by erikng** [comment]
I can, but I somewhat think they are in line with each other.

Right now I can silently update login-once scripts and they won't rerun. This behavior would change with this update.

**Comment by chilcote** [comment]
Ah OK I see what you are saying.  Let me see if I have this right:

Currently, if you change a script but keep the name, future users who login will run it, but any users who have already run the preceding version of the script won't run it again because the plist is only checking the file name.

With this proposed change, if you change the script it will change the checksum, so _all_ users, future and existing, would run it again.

---

The proposed change in this issue is at odds with how you prefer it to behave.

**Comment by erikng** [comment]
Si senor. :)

A good example would be setting up docks. Let's say I update my dock script to add Office 2016, but only if Office 2016 is installed. Right now I can safely do that and not touch current users' docks.

**Comment by aysiu** [comment]
Can we talk a bit more about use cases?

Is a login-once script really a login-once script if it's supposed to be run a second time? I can see rewriting a script, as @erikng said, to update the default Dock for new users so keeping the name and not running it again makes sense, but I'd love to hear more about specific cases of why someone would want to update a login-once script and have it run again for all users... without just calling it something else.

I think the current behavior makes sense.

**Comment by chilcote** [comment]
Yeah, that's precisely why I've been ignoring this (besides the fact that I'm terribly lazy). I understand the desire to have tidy script names, but tying it to a checksum will have other, perhaps unintended, consequences. 

Back when I gave this some small amount of thought, I couldn't reconcile these two desired behaviors:

1. Updating a script but keeping the name and having it apply to existing and new user logins.
2. Updating a script but keeping the name and having it apply to only new user logins.

Maybe someone else has a clever idea?

**Comment by aysiu** [comment]
That could make everyone happy, I think. Just out curiosity, though, I'd love to hear what people need this functionality for. Sometimes it helps to know this stuff, because it can help me reevaluate how I do things ("Oh, I never thought of approaching it that way...").

Without use cases, I tend to think of login-once as set-once default settings that the user can change and then login-every as set-every forced settings you want users to always have. If I screwed up the login-once, I still wouldn't want it to apply retroactively to users who have already customized their environments.

Not curmudgeonly—just curious.

**Comment by chilcote** [comment]
I think some people just want to avoid having scripts named `configure_dock.sh`, `configure_dock_May_2016.sh`, `no_really_configure_dock_for_everyone.sh`, etc, cluttering up the directories over time.

Also, there is the case where `configure_dock.sh` for some reason doesn't work completely as expected, and the admin updates it and pushes it out, but forgets that outset won't run it again even though it didn't do what she wanted the first time, because she didn't append a date stamp or some other identifier to the script name. (Note, for scripts that _fail_ with an error code, it won't get added to the plist so the script will try and try again ad nauseum). 

Ultimately, it's probably good practice to only use login-every scripts and write them to be idempotent. But who's got time for that? 

I'm comfortable with the current implementation (file name checking only), but I can be convinced there's a better way.

**Comment by erikng** [comment]
I agree with the login-every comment. That's exactly what I did to get around it and it worked well. 

While the PR is clever, I'm not sure it's worth the hassle. Is anyone besides Allister actually wanting this feature? Does he even want the feature now?

**Comment by clburlison** [comment]
> Ultimately, it's probably good practice to only use login-every scripts and write them to be idempotent. But who's got time for that?

That's actually the main reason why this is still of interest to me.

Use-Cases: changing the dock is the main one, however any script that uses defaults in the context of the end user. There are many settings that I want to help push people towards, mostly because it helps both of us. However I might not want them applied on every run.

Basically using a sha1 hash allows a new login type that more closely matches the mcx 'often' (at least in my opinion). With that said if seems worth wild it might just be easier to make a new login type, `login-often` that hashs the script when it's ran. Then we have no chance of breaking anything with the current implementation of 'once' or 'every'.

Lastly, if this idea gets cut it isn't the end of the world. If you use puppet to set your scripts puppet already does the version hashing for you then you just run a script when things get changed. https://github.com/clburlison/puppet-outset/blob/master/files/remove_once.sh 

My two ¢

**Comment by clburlison** [comment]
Also, my complaint with doing something like 
> `configure_dock.sh`, `configure_dock_May_2016.sh`, `no_really_configure_dock_for_everyone.sh`

is now outset must run all of those scripts so you as the admin have to make sure the final run order of those scripts is going to do what you want. If you forget that key point, it's very possible that you'll have two machines that should have the same configuration but end up looking different because one was imaged 5 months ago and this new one 2 days ago ran the scripts in a different order. Obviously this is just an extra gotcha that I don't want to deal with.

**Comment by chilcote** [comment]
@clburlison Just so I'm clear, you deal with multi-user Macs regularly, right? I've never been in that scenario but I can see how having multiple similar (in name and function but not relevance) scripts can be problematic. Thanks for the examples

**Comment by clburlison** [comment]
Yes. Multiuser.
On Sat, May 21, 2016 at 10:50 AM Joseph Chilcote <notifications@github.com>
wrote:

> @clburlison <https://github.com/clburlison> Just so I'm clear, you deal
> with multi-user Macs regularly, right? I've never been in that scenario but
> I can see how having multiple similar (in name and function but not
> relevance) scripts can be problematic. Thanks for the examples
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/chilcote/outset/issues/20#issuecomment-220785031>
>
-- 
Clayton Burlison
@clburlison
https://clburlison.com

**Comment by erikng** [comment]
The MC X "often" is an interesting point. That's a great use case.

**Comment by chilcote** [comment]
Thinking about the "often" concept and looking at https://github.com/clburlison/puppet-outset/blob/master/files/remove_once.sh, another scenario comes to mind: What if the admin wants to run the same script again for all users, but isn't technically updating the script, and as such, the sha1 hash wouldn't have changed?

Using our dockutil use case, what if the admin wants to, for some reason, reset everyone's dock back to the default, using the same exact script as before?  

In the current implementation of Outset, she would have to create a newly named script and push that out, but new users would run both the original _and_ the newly named script. In the PR's implementation, she would have to add a line to the script with "Update=True" (and make sure it's the right line!) and then push that out, and Outset would do the sha1 dance. Neither of these solutions makes me happy.

Let's take a step back, and take a look at the core problem(s) we are trying to solve in this issue: 

We want Outset to behave properly in both of these scenarios:

1. Update script in place and have it only apply to new subsequent logins
2. Update script in place and have it apply to all subsequent logins, whether they've run the script before or not

The current Outset implementation behaves thusly:

- Scenario 1 solution: Admin updates the script but maintains the script's name
- Scenario 2 solution: Admin updates the script and changes the script's name

Which has these problems:

- In the second solution above, subsequent new logins will _also run the originally named script_
- What if the admin's intent is to run the exact same script again, for users who have aleady run it (think: "often")

-----
**My crazy idea:**

Let's put aside the whole idea of using a sha1 hash for a later discussion.

Since "often" is a timey-wimey concept, what if instead, Outset checks the timestamp of when the script was run (which is information we have already been gathering since Outset 0.0.1), and compares that against a timestamp that is defined by the admin at the time the script is updated. Thus, Outset will only _re-run_ a login-once script if it A) exists in the user's run-once plist AND B) exists in the Outset prefs plist with a timestamp that, via comparison, returns as "later" than the last time the script was run?

I threw together a branch this morning to try this idea out. Can someone(s) test this branch to see if it solves addresses the main thrust of this issue? 

https://github.com/chilcote/outset/tree/updating_scripts

Define a login-once script you want to run again for _all_ users with the following:

    sudo /usr/local/outset/outset --add-override my_awesome_dockutil_script.sh

**Comment by erikng** [comment]
Looks good. My implementation with login-every was exactly that: a time stamp.

**Comment by rodchristiansen** [comment]
Currently what I am doing is adding version numbers to the scripts in `login-once` such as `AdminFinder-10.11.3.sh` or `StudentFavoriteServers-10.11.1.sh`

When I update the script, say `StudentSystemPrefs-10.11.1.sh` to `StudentSystemPrefs-10.11.2.sh` and I have been adding postinstall scripts in the package to remove the old one to prevent clutter, even though I know that script is in the loginonce plist so it doesn't run again.

This override idea sounds like a great solution to this.

**Comment by chilcote** [comment]
Definitely try it out and let me know if it's a viable solution for you.

**Comment by majorsl** [comment]
I'm late to the thread, but can outset look inside a script for a properly formatted comment to know if it should re-run a script?  A version string as a comment would be enough to trigger it.  Similar to what rodchristiansen mentions, just within a script.

Default with no matching string is to not run again.  There are times I want a script to never run if it already has, regardless if I update the script or not across all my systems.

**Comment by chilcote** [comment]
That's not the direction I went with [https://github.com/chilcote/outset/tree/updating_scripts](https://github.com/chilcote/outset/tree/updating_scripts).  As long as you don't change the name of the script, it won't run again unless you call it out in the plist.

Ultimately, I believe that the best solution for this sort of thing is to make the scripts idempotent and put them in `login-every`, to ensure that the setting you intend is only changed if needed.  Then you can update that script at will.  Login once is great for "settings that are stuck in time," but not really ideal for "settings that evolve over time."  However, that branch should give the admin the flexibility to re-use scripts in `login-once` if needed.

My solution may be too clever, and I'm happy to take more feedback.  If enough people think it's worth it, I'm happy to merge.  Honestly, I haven't really had time or need to do more testing on this feature.

**Comment by erikng** [comment]
I agree with Joe, but here is a suggestion: create your own timestamp mechanism and run it with login-every. I did this at my last job and the script would only rerun if the time stamp on the script was newer than the last expected time stamp.

There's many ways to work around this with zero changes to outset that could impact other users.

Sent from my iPad

On Dec 10, 2016, at 9:27 PM, Joseph Chilcote <notifications@github.com<mailto:notifications@github.com>> wrote:


That's not the direction I went with https://github.com/chilcote/outset/tree/updating_scripts. As long as you don't change the name of the script, it won't run again unless you call it out in the plist.

Ultimately, I believe that the best solution for this sort of thing is to make the scripts idempotent and put them in login-every, to ensure that the setting you intend is only changed if needed. Then you can update that script at will. Login once is great for "settings that are stuck in time," but not really ideal for "settings that evolve over time." However, that branch should give the admin the flexibility to re-use scripts in login-once if needed.

My solution may be too clever, and I'm happy to take more feedback. If enough people think it's worth it, I'm happy to merge. Honestly, I haven't really had time or need to do more testing on this feature.

-

**Comment by chilcote** [comment]
Do you have an example function you can throw into the wiki perchance?

**Comment by erikng** [comment]
Not sure if I can legally do that, but I will reach out to them or have the current maintainer post it.

**Comment by chilcote** [comment]
I'm going to go ahead and merge this change.  It's a non-breaking change, so existing outset installs won't be affected. But for admins who want to make use of the script overrides, this may prove handy.  I've updated the wiki here: https://github.com/chilcote/outset/wiki/ScriptOverrides

As soon as I get a thumbs up on Issue41 I'll push these changes.
