### ISSUE TITLE
ERROR: Bad Permissions and login-once

### ISSUE THREAD

**Issue by rmanly** [chilcote/outset#21]
If **just for example** *COUGH* someone happens to forget to set a login-once script +x, outset will log the error but also never run that script again if fixed later

To Reproduce:

*forget* to set a login-once script as executable before packaging it up with something that isn't theluggage, let's say for example…oh I don't know munki-pkg.

Behavior:

+ outset will run
+ ~/Library/Logs/outset.log will record "ERROR: Bad Permissions /usr/local/outset/login-once/foo.bash"
+ user's run_once_plist is written to with scriptname

Problem:

There is something wrong with the logic such that check_perms logs "ERROR: Bad Permissions" but the com.github.outset.once.plist is still written to. This prevents the admin from being able to version bump that script after setting proper permissions and repackaging, and then deploy again without modifying or destroying the once.plist.

At a quick glance it *appears* that if the perms are checked on line 213 then the once.plist should not be written to on line 223.

I am just looking in passing at the moment as I don't have much time.

**Comment by chilcote** [comment]
Looking into this finally.

If the permissions are bad, then you are correct and it won't flag that script as having been run. However, if there is an error running the script (no shebang, for insance), in the current state it will add it to the plist and not try to run again if the admin bumps it.  This issue was reported in the macadmin slack channel too.

This will be fixed in the next push.  The new behavior will be such that if the script has bad perms, or returns an error code, then outset will not add it to the run once plist.
