### ISSUE TITLE
Profiles stored in login-every cause a Configuration Profile Tool dialog to appear

### ISSUE THREAD

**Issue by carlashley** [chilcote/outset#43]
If a `mobileconfig` profile is placed in `/usr/local/outset/login-every`, on logins following the first login in which the profile is installed, a dialog box will appear (as attached).

Moving the profile to `/usr/local/outset/login-once` resolves this issue, however the behaviour of being able to have the profile "updated" by simply changing the profile in `login-every` and having the user logout and log in is lost. This is a much quicker method than using `login-once` overrides.

![screen shot 2017-01-11 at 10 06 32 am](https://cloud.githubusercontent.com/assets/9841187/21832264/924f3d30-d7f5-11e6-93c4-a59d37a4a149.png)

**Comment by erikng** [comment]
Have you tried calling the profile with -IvF?

On Jan 10, 2017, at 6:05 PM, Carl <notifications@github.com<mailto:notifications@github.com>> wrote:


If a mobileconfig profile is placed in /usr/local/outset/login-every, on logins following the first login in which the profile is installed, a dialog box will appear (as attached).

Moving the profile to /usr/local/outset/login-once resolves this issue, however the behaviour of being able to have the profile "updated" by simply changing the profile in login-every and having the user logout and log in is lost. This is a much quicker method than using login-once overrides.

[screen shot 2017-01-11 at 10 06 32 am]<https://cloud.githubusercontent.com/assets/9841187/21832264/924f3d30-d7f5-11e6-93c4-a59d37a4a149.png>

-

**Comment by chilcote** [comment]
Does the same thing happen if you manually install a user profile twice, or is this behavior specific to outset?

**Comment by WardsParadox** [comment]
I notice this when the account is not an admin, and the profile is being installed every time it logs in after it has been loaded once and is simply refreshing it. I'll test it when I get a chance for both a profile updated and just a repeat of the same profile.

**Comment by chilcote** [comment]
I installed a profile manually with `profiles -IvF` and then immediately installed the profile again.  I see this same message.  Since this is behavior seen in vanilla MacOS, I'm not really sure what's being proposed here?

I would have suggested scripting the uninstall/reinstall of the profile at `login-every` but, alas, running `profiles -RvF`  also prompts the user with this message. 

I suppose we could wrap it in some logic that checks the Payload Identifier to see if it's already been installed, but then that's just replicating the `login-once` structure, and would not account for when you want it to be forcibly re-installed.

What exactly did you have in mind?

**Comment by erikng** [comment]
Are you guys perhaps installing system level profiles and not user level ones? You have to change the payload itself in the profile.

On Jan 10, 2017, at 10:00 PM, Joseph Chilcote <notifications@github.com<mailto:notifications@github.com>> wrote:


I installed a profile manually with profiles -IvF and then immediately installed the profile again. I see this same message. Since this is behavior seen in vanilla MacOS, I'm not really sure what's being proposed here?

I would have suggested scripting the uninstall/reinstall of the profile at login-every but, alas, running profiles -RvF also prompts the user with this message.

I suppose we could wrap it in some logic that checks the Payload Identifier to see if it's already been installed, but then that's just replicating the login-once structure, and would not account for when you want it to be forcibly re-installed.

What exactly did you have in mind?

-

**Comment by carlashley** [comment]
@erikng - no - this is relying on `outset` to do the profile installation (so unscripted profile install)

@chilcote - would have to test manual installs twice.

@WardsParadox - yeah, thats pretty much the behaviour I'm seeing. The profile hasn't actually changed, and the user is _not_ an admin.

On reflection away from work, I think the `login-once` overrides is a better way for me to handle it.

I have also been thinking that perhaps the `login-once` behaviour for profiles could be:
1. Initial install
2. Add the file's last modified timestamp (LMT) to the override
3. On next run compare existing file LMT to the override timestamp and if the file has a newer LMT, remove the old, install the new.

**Comment by chilcote** [comment]
Two problems:  1) login items are processed in the user context, and the user can't edit the plist in /usr/local/outset/share to update an override, and 2) removing the profile invokes the same pop up. 

![jan-11-2017 06-33-40](https://cloud.githubusercontent.com/assets/305026/21852518/31e17026-d7c8-11e6-97c3-ab9106fe7883.gif)

**Comment by WardsParadox** [comment]
I find it easier to just use a `login-once` to install the profile and if it needs to be updated, I update a script + profile name to ensure a fresh run.

**Comment by carlashley** [comment]
No worries, lets consider this issue closed ;)
