### ISSUE TITLE
wrong permission for /usr/local/outset/share/com.chilcote.outset.plist

### ISSUE THREAD

**Issue by vikaskedia** [chilcote/outset#53]
## This does not work

Inside /usr/local/outset/boot-once/boot-once.sh I set:

defaults write /usr/local/outset/share/com.chilcote.outset.plist wait_for_network false

This results in:
/usr/local/outset/share/com.chilcote.outset.plist to have the permission set -rw------- root:wheel

This results in the login-every script not executing.
![image](https://user-images.githubusercontent.com/6703876/34459218-84bf43a8-ed9e-11e7-9ddd-508d1575c89b.png)

## This works

If I do not set "defaults write /usr/local/outset/share/com.chilcote.outset.plist wait_for_network false
" inside /usr/local/outset/boot-once/boot-once.sh then the permissions are:

![image](https://user-images.githubusercontent.com/6703876/34459262-2b029124-eda0-11e7-8203-879f376ba12d.png)

**Comment by gregneagle** [comment]
I don't see how this is an issue/problem with Outset. This is a problem with your boot-once.sh script. `defaults` always sets the mode of files it writes to 600. You should fix/change your script to reset the mode to 644 after using `defaults`.

**Comment by chilcote** [comment]
Verified the permissions are correct when installed. This has come up before, and is probably due to the wiki recommending using `defaults` to manipulate this (non-preference) plist, which is probably bad advice. I updated the wiki https://github.com/chilcote/outset/wiki/NetworkTimeout to include a note about permissions.

**Comment by vikaskedia** [comment]
tx
