### ISSUE TITLE
How to install homebrew using outset?

### ISSUE THREAD

**Issue by vikaskedia** [chilcote/outset#55]
# Option 1:

The content of brew-install.sh is:
vk@vks-Mac ~> more /usr/local/outset/login-privileged-every/brew-install.sh 
#!/bin/bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

When I run it in login-privileged-every the error i get is:

2018-01-02 01:28:49 AM - ERROR: Failure processing /usr/local/outset/login-privileged-every/brew-install.sh: Don't run this as root!

# Option 2:
When I run it in login-every the error i get is:

2018-01-02 01:17:44 AM - ERROR: Failure processing /usr/local/outset/login-every/brew-install.sh: sudo: no tty present and no askpass program specified
Failed during: /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin /usr/local/etc /usr/local/share /usr/local/share/man /usr/local/share/man/man1

**Comment by chilcote** [comment]
My guess is that it has something to do with the context in which the script is being run (launchd). Also, I'm not sure brew is supposed to be installed with privileged access, but I don't know because I don't install it.

Since this is not an issue with Outset itself, I'm going to respectfully refer you to the [macadmin slack](https://macadmins.herokuapp.com/) where there are thousands of mac admins, some of whom may have already solved your scripting questions. Cheers!
