### ISSUE TITLE
login-privileged-once not executing on Big Sur 11.6

### ISSUE THREAD

**Issue by z3ky** [chilcote/outset#86]
The script in login-privileged-once is not executed. There are no error logs or something else.

I put this script in login-privileged-once

[https://community.jamf.com/t5/jamf-pro/managing-mouse-button-behavior-in-modern-macos/td-p/214384](url)

and set permissions to execute the file.

In login-once the script will be executed but with errors due to missing privileged permissions.

**Comment by arubdesu** [comment]
Hey @cass, thanks for including the script in question you're trying to execute. I'm afraid this isn't an outset bug, I can tell you for certain Big Sur has no issues running login-privileged-once scripts, you'll need to figure out if your actual problem is that you're running into TCC/PPPC issues (where the python interpreter you're calling isn't allowed to perform a certain action). For more help feel free to join MacAdmins slack (macadmins.org) and ask for assistance in the #outset or #python channels.

**Comment by arubdesu** [comment]
@chilcote (I'd think we can close this as it's not proven to be an issue with outset itself)

**Comment by chilcote** [comment]
🍺

**Comment by z3ky** [comment]
Sorry for the late response. Yes no bug, it works.
